### ISSUE TITLE
出力に垂直タブが含まれると結果が表示されない

### ISSUE THREAD

**Issue by Khronos31** [jiro4989/websh#143]
これはNimのjsonモジュールの問題です。
'\v'はJSONでサポートされていないため、本来は'\u000b'としなければいけないのですが、Nimのjsonモジュールは正しくエスケープしていません。Nimの問題が修正されるまでの暫定措置として、'\v'を'\u000b'に置換する等が考えられます。

**Comment by jiro4989** [comment]
@Khronos31 
ありがとうございます。こちらのPRをだしてくださってのですね。
https://github.com/nim-lang/Nim/pull/13399

暫定で置換処理を入れるようにします。

**Comment by jiro4989** [comment]
#156 でアプリをビルドするNimコンパイラのバージョンを 1.2.0 にあげました。
こちらのバージョンでは今回の問題は解消されています。
解消したのでクローズします。
