### ISSUE TITLE
Tweetボタンのハッシュタグが付与されない

### ISSUE THREAD

**Issue by eggplants** [jiro4989/websh#169]
お世話になってます。
GETパラメータに今`button_hashtag=シェル芸`を使われていますがうまくボタンを押した際に付与されません。`hashtags=シェル芸`の方が良いかもしれないです。

**Comment by jiro4989** [comment]
いつのまにか付与されなくなってたことに気づいてましたが、完全に忘れてました

**Comment by jiro4989** [comment]
@eggplants  直しました。まだハッシュタグがつかないなどありましたら、ブラウザのキャッシュを削除して画面を読み込み直していただければ。

**Comment by eggplants** [comment]
ありがたいです…
