### ISSUE TITLE
スクリプトをURLで

### ISSUE THREAD

**Issue by eggplants** [jiro4989/websh#181]
例えばGETパラメータにプログラムをもたせるなど
```text
https://websh.jiro4989.com/?s=echo%20Hello%2C%20world
```
で、`echo Hello, world`がtextareaに入力された状態でいてほしいです。
これだとシバンを持たせたリンクをブックマークしておくとかで便利に使えそうです。
ご検討よろしくおねがいします。

**Comment by eggplants** [comment]
#160 
> クエリパラメータがあると自動でセットされるようにするくらいなら簡単そう

まさにこれですね…

**Comment by eggplants** [comment]
mergeされれば
```
https://websh.jiro4989.com/?code=echo%20Hello%2C%20world
```
でいけそうですね　感謝です

**Comment by eggplants** [comment]
変更は反映されていますか？

**Comment by jiro4989** [comment]
いい感じに動いてくれなくて放置してますね

**Comment by jiro4989** [comment]
- コンパイラのバージョンを上げた
- フロントエンドフレームワークのバージョンを上げた
- コードを修正した

ら、以前詰まってた不具合が直ったのでリリースしました。
ご確認ください

**Comment by eggplants** [comment]
<https://websh.jiro4989.com/?code=echo%20Hello%2C%20world>

![image](https://user-images.githubusercontent.com/42153744/100261994-e512ad00-2f8e-11eb-85c1-4f1d8fe0f69b.png)


確認しました。ありがとうございます！

**Comment by eggplants** [comment]
#160 は<https://websh.jiro4989.com/?code=%23%21%2Fusr%2Fbin%2Fenv%20python>とかをブックマークしておくと良さそうですね
