### ISSUE TITLE
images欄をpngからgifに

### ISSUE THREAD

**Issue by eggplants** [jiro4989/websh#189]
お世話になってます。
現在webshで実行した結果はimages欄に`data:image/png;base64`で表示されますが、apngが表示される時、それをそのまま保存してTwitterに投稿しようと思うとローカルで`mogrify -format gif *.png`しないといけません。出来れば`data:image/gif;base64,`で表示していただけると嬉しいです。

**Comment by jiro4989** [comment]
シェル芸bot内でアニメーションGIFを作って画面に返した時に、画面上では全部PNGとして表示されてダウンロードした時に困るのでアニメーションGIFの時はGIFとして画面に出して欲しい、という要望ですね？

```bash
seq 9 | textimg -as
```

**Comment by jiro4989** [comment]
とりあえず改修してみましたのでご確認ください

**Comment by eggplants** [comment]
<https://websh.jiro4989.com/?code=eval%20unko.shout%5C%20%7Bhey%2C%E3%80%80%2Cyou%2C%E3%80%80%7D%5C%3B%7Clolcat%20-f%7Ctextimg%20-asl8%20-d100>

![image](https://user-images.githubusercontent.com/42153744/100262466-86016800-2f8f-11eb-9024-8b8ce77ddc72.png)

確認しました。爆速対応ありがとうございます！
