### ISSUE TITLE
AndroidのChromeで実行できない場合がある

### ISSUE THREAD

**Issue by eggplants** [jiro4989/websh#203]
AndroidのChrome上で: <https://websh.jiro4989.com/?code=echo%20test>
のようなリンクを開き、再度websh上に表示されている同リンクを開いた時、`Run`をタップしても実行されなくなります。PCのChromeでは再現しませんでした。
(あまり対応しなくても良いかも知れませんが…)

**Comment by jiro4989** [comment]
#181 を入れた時からAndroidで操作したときに動かなくなるのは気づいていましたけれど
スマホで動作検証するのかなり面倒なので放置してますね。
気が向いたら調べるかもしれません

**Comment by eggplants** [comment]
wontfixですか？

**Comment by jiro4989** [comment]
特に対応する気がないので閉じました
