### ISSUE TITLE
paizaio bot向けモード

### ISSUE THREAD

**Issue by eggplants** [jiro4989/websh#226]
`@paiza_bot bash:コード`(か`#paiza_bot bash:コード`)で呟けるモードがあると<https://twitter.com/paiza_bot>向けのツイートが作成できて便利です。

`@paiza_bot`と`@minoyruminyon`で環境やコマンドなどは違いますが、おまけ程度に用意していただけるとありがたいです。

### `paizaモード`オフ

- 従来どおり

![image](https://user-images.githubusercontent.com/42153744/172459913-1289d802-5213-4a3b-9662-a4ca9b2bc022.png)

### `paizaモード`オン

- シェル芸Bot向けハッシュタグなし
- `Tweet`押下で`@paiza_bot bash:コード`を本文に持つツイート投稿画面

![image](https://user-images.githubusercontent.com/42153744/172459961-e5031c04-bee3-4ace-b2f6-2b0bc0f96146.png)

**Comment by jiro4989** [comment]
ちょっと考えます

**Comment by jiro4989** [comment]
paizabotの実行環境でプログラムを動作させることを鑑みるに、
webshに機能をつけるよりは paiza.io の方に機能要望でTwitterに投稿できる機能を依頼するのがあるべき姿でしょう。

https://paiza.io/ja/projects/new

シェル芸Botとpaiza botは実行基盤も全く違うわけですし、paizaモードを追加する必要性を感じません
