### ISSUE TITLE
末尾の改行を削除しないで欲しい

### ISSUE THREAD

**Issue by Khronos31** [jiro4989/websh#63]
出力の末尾の改行文字が取り除かれます。これは仕様でしょうか？
Request Body
{"code":"echo 'abc\ndef'"}

Response Body
{
    "status": 0,
    "system_message": "",
    "stdout": "abc\ndef",
    "stderr": "",
    "images": []
}

(参考: SGWebの場合)
Request Body
{
    "code": "echo 'abc\ndef'"
}

Response Body
{"stdout": "abc\ndef\n", "stderr": "", "sysmsg": "", "images": []}

**Comment by jiro4989** [comment]
末尾の改行を削除する処理をしているのではなく、各行を改行文字で結合するように処理しています。

https://github.com/jiro4989/websh/blob/7dda422e72ef1decb985dd03c8ffefc0cb95a86d/websh_server/src/websh_server.nim#L31-L36

なので、以下のように改行文字を最後に残した場合も改行文字は残ります。

```bash
curl -X POST -d "$(gjo -p code='echo -e "abc\ndef\nghi\n\n\n"')" 'https://websh.jiro4989.com/api/shellgei'\n
```

> {"status":0,"system_message":"","stdout":"abc\ndef\nghi\n\n\n","stderr":"","images":[]}

[gjo](https://github.com/skanehira/gjo) json文字列を生成するコマンド

**Comment by jiro4989** [comment]
APIのレスポンスに改行を含めているのが正しいのか、含めていないのが正しいのかについては特に考えていませんでした。
この場合どちらを正とするかについて決定する必要があります。

どちらを正にするかの判断基準は、SGWebではなくシェル芸botを基準にしようと思っています。
シェル芸botがどういうテキストを返却するか、をなるべく再現する形にしようかと思っています。

**Comment by jiro4989** [comment]
ここでいう「シェル芸botが」というのはTwitter側で自動で空白や改行が自動で削除されるものは含めません。[ShellgeiBot](https://github.com/theoremoon/ShellgeiBot)がどういう風にテキストを処理してTwitterAPIに渡しているか、を指します。

**Comment by Khronos31** [comment]
そうしますと、Twitterの文字数制限に収まるようにトリミングする処理や、あるいはタイムアウトした際の挙動が異なると思いますが、どの程度まで再現しようとお考えでしょうか。

**Comment by jiro4989** [comment]
まず出力をAPI側で制限することは現状考えていません。暇になったらやるかもくらいの感覚です。
サーバ側で超過した分を捨ててから返却すると、超過しても良いから結果を確認したいというニーズを満たせないためです。

超過しているか、していないかの判定結果を合わせてAPIから返却すること、
およびその結果を画面上に表示することについては考えています。
パラメータの有無でデータをTwitterの制限内に納めて返却するようにもできるとは思いますが、対応するなら当分さきですね。

データ制限の処理を設けてもAPIのユーザとしては使いづらくなることのほうが多いというのが私感で、優先度的には低いと考えています。


次に、どこまで再現するか、については僕のモチベーションと僕が必要だと感じたかで決めます。
Twitterの仕様に追従するのは個人的にはかなりコストが高く、自分が実装するのだとしたら後回しにしたいです。

仮にTwitterの仕様を可能な限り追従するとして、
実装するときに今思いついたかぎりで以下の点が気になりました。

* 文字列の何が切り捨てられるのか
* 文字数のカウントはどうやっているのか
* 禁止ワードの扱いはどうするか
* 引用リツイート時に付与されるURLを考慮する必要があるか
* 不可視文字などの扱いはどうするか
* URLの扱いはどうするか
* 扱える画像サイズの上限はどうなっているか

これらがドキュメントに明文化されていればよいですが、
見つからなかったときに払うコストはかなりのものです。

これらのコストを支払って得られるものが細かい挙動の微調整程度なら、
僕はUI改善やパラメータの追加を優先してアプリを改良するほうに舵をきります。

自分以外の誰かが改良のPRなどを出すのならおそらく受け入れるとは思いますが、
自分が実装する分にはそれらは優先度を下げます。

**Comment by jiro4989** [comment]
「つぶやきの先頭の空白と最後の空白の連続は切り捨てられる」
が厳密に何の文字が切り捨てられるのかまでは知りませんが、
とりあえず半角スペースと全角スペースとタブ文字くらいは捨てるか。

くらいの雑さでの改良ならまぁやろうかな、という具合です。
その場合はPOST時のパラメータの有無でレスポンスを切り替える形になりますかね

**Comment by jiro4989** [comment]
Twitterの仕様にどこまで追従するかは置いといて、
シェル芸botと異なる挙動をしていた改行が除かれる不具合は修正しました。
ありがとうございました。
改行が除かれる不具合については対処したので課題をクローズします。

1つのissuesで複数の課題について議論するべきではないので、
Twitterの仕様追従について議論したいのでしたら、別途課題を起票してください。
